[package]
name = "json-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
humansize = "2.1.3"
num-format = "0.4.4"
rayon = "1.11.0"
thiserror = "2.0.16"
